# Generated by Django 3.2.6 on 2021-08-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenoes',
            new_name='linenos',
        ),
    ]
